name: GitHub Pages

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the workflow from
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build the site
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: jamesives/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: _site  # The folder to deploy from
